'use strict';

const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const SITE='https://madedeck.com';

const pages={
  'custom-t-shirts':{
    title:'Custom T-Shirts | Design, Print and Sell Your Own | MadeDeck',
    description:'Design custom t-shirts, preview your artwork, order one or publish products to your MadeDeck store. No minimum order.',
    eyebrow:'CUSTOM T-SHIRTS',headline:'Your ideas wear better here.',lede:'Create custom t-shirts for your brand, business, team, event, or personal project. Preview the design before ordering or publishing it to your store.',
    image:'/seo-assets/custom-t-shirts.webp',cta:'Start designing',ctaHref:'/?product=tee#designer',secondary:'See shirt options',starting:'Starting at $18',product:{name:'MadeDeck Custom T-Shirt',sku:'tee',price:'18.00'},
    benefits:['No minimum order','Human artwork review before production','Multiple garment colors and sizes','Order directly or publish to your store'],
    uses:['Businesses','Events','Schools and teams','Creators and merch'],
    faqs:[['Is there a minimum order?','No. You can order one shirt or build a larger order.'],['What artwork files work best?','High-resolution PNG and vector artwork generally produce the strongest results.'],['Can I sell shirts through my store?','Yes. Save the product, publish it to your storefront, and share the product or store link.'],['How long does production take?','Timing depends on the garment, decoration method, quantity, and destination. The current estimate is shown during ordering.']]
  },
  'custom-hoodies':{
    title:'Custom Hoodies | Design and Sell Branded Hoodies | MadeDeck',description:'Create custom hoodies with realistic previews, flexible quantities, and an option to publish products to your MadeDeck store.',
    eyebrow:'CUSTOM HOODIES',headline:'More than a hoodie. Make it yours.',lede:'Build custom hoodies for brands, teams, schools, events, and creators. Choose a style, add artwork, preview it, then order or publish.',
    image:'/seo-assets/custom-hoodies.webp',cta:'Start designing',ctaHref:'/?product=hoodie#designer',secondary:'See hoodie styles',starting:'Starting at $26',product:{name:'MadeDeck Custom Pullover Hoodie',sku:'hoodie',price:'26.00'},
    benefits:['Pullover and premium blank options','Front, back, and sleeve decoration support','Sizes and color choices vary by garment','Order directly or publish to your store'],uses:['Businesses','Events','Schools and teams','Creators and merch'],
    faqs:[['Can I order one hoodie?','Yes. MadeDeck supports one-off orders as well as larger quantities.'],['What sizes are available?','Sizes depend on the selected blank. Available choices appear with the product.'],['Can I preview the design?','Yes. The Studio provides a visual preview before you save or order.'],['Can customers buy from my store?','Published products can be offered through your MadeDeck storefront.']]
  },
  'custom-hats':{
    title:'Custom Hats | Embroidered and Printed Hats | MadeDeck',description:'Design custom hats for brands, teams, events, schools, and merchandise stores with preview and storefront options.',
    eyebrow:'CUSTOM HATS',headline:'Wear your ideas.',lede:'Create custom hats for a brand, team, event, or creator store. Pick a style, place your artwork, review the result, and choose whether to order or publish.',
    image:'/seo-assets/custom-hats.webp',cta:'Start designing',ctaHref:'/?product=hat#designer',secondary:'See hat styles',starting:'Starting at $27',product:{name:'MadeDeck Custom Premium Snapback',sku:'hat',price:'27.00'},
    benefits:['Multiple hat shapes and color options','Embroidery and supported decoration methods','Artwork reviewed before production','Designed for orders and storefront products'],uses:['Businesses','Events','Schools and teams','Creators and merch'],
    faqs:[['What hat styles are available?','Available styles may include snapbacks, trucker hats, dad hats, five-panel hats, beanies, and flexible-fit options.'],['Is there a minimum order?','No minimum is required for supported styles.'],['Can a hat be added to my store?','Yes. Save and publish an eligible hat product to your storefront.'],['How is pricing calculated?','Final pricing depends on the blank, decoration method, artwork, and quantity.']]
  },
  'custom-stickers':{
    title:'Custom Stickers and Labels | Small Packs and Bulk Runs | MadeDeck',description:'Create square custom stickers and labels for products, packaging, promotions, events, and merchandise.',
    eyebrow:'CUSTOM STICKERS',headline:'Stick it. Brand it. Share it.',lede:'Turn artwork into custom square stickers and labels for product packaging, giveaways, events, and everyday promotion.',
    image:'/seo-assets/custom-stickers.webp',cta:'Start designing',ctaHref:'/?product=sticker2#designer',secondary:'See sticker sizes',starting:'2×2, 3×3, and 5×4',product:{name:'MadeDeck Custom Stickers and Labels',sku:'stickers-labels',lowPrice:'45.00',highPrice:'70.00',offerCount:3},
    benefits:['Single samples and supported pack quantities','Durable vinyl options','Useful for labels, gifts, packaging, and promotion','Artwork preview before ordering'],uses:['Product businesses','Events','Schools and teams','Creators and merch'],
    faqs:[['What sticker sizes are offered?','The current catalog includes 2×2 and 3×3 square stickers plus 5×4 labels.'],['Can I order packs?','The current sticker and label products are sold in 200-piece packs.'],['Can I upload my own logo?','Yes. Upload your artwork in Studio and review the placement before ordering.'],['When will my stickers ship?','The order flow shows the current production and delivery estimate for the selected option.']]
  },
  'online-merch-store':{
    title:'Online Merch Store | Create and Sell Branded Products | MadeDeck',description:'Launch an online merch store with custom products, checkout, order management, printing, packing, and fulfillment connected.',
    eyebrow:'ONLINE MERCH STORE',headline:'Sell your ideas. We handle the rest.',lede:'Create products, build a branded storefront, publish your collection, and share one link. MadeDeck keeps creation, checkout, orders, and production connected.',
    image:'/seo-assets/online-merch-store.webp',cta:'Start your store',ctaHref:'/?page=join',secondary:'See how it works',starting:'Start free',
    benefits:['Branded public storefront','Products, checkout, and orders in one flow','No inventory purchase required to begin','Shareable store and product links'],uses:['Creators and influencers','Small businesses','Schools and teams','Events and organizations'],
    faqs:[['Is there a minimum order?','No. Store products can support individual customer orders.'],['How do I set up my store?','Create an account, make or save products, configure the storefront, then publish it.'],['How do I get paid?','The applicable checkout, fees, credits, and account economics are shown in your account and order records.'],['Who handles fulfillment?','MadeDeck connects paid orders to artwork review, production, packing, and shipment.']]
  },
  'print-on-demand-for-small-business':{
    title:'Print on Demand for Small Business | Branded Products and Stores | MadeDeck',description:'Use print on demand to create branded products, launch a storefront, and fulfill customer orders without buying inventory first.',
    eyebrow:'PRINT ON DEMAND FOR SMALL BUSINESS',headline:'Your brand. Real products. No inventory pile.',lede:'Create branded products for a cafe, shop, studio, service company, team, or local organization. Publish a store and sell without purchasing a warehouse of stock first.',
    image:'/seo-assets/print-on-demand-small-business.webp',cta:'Start your store',ctaHref:'/?page=join',secondary:'See how it works',starting:'Built to start small',
    benefits:['No upfront inventory requirement','Branded storefront and checkout','Product and order management','Production review and fulfillment workflow'],uses:['Restaurants and cafes','Local services','Realtors and real estate','Schools, teams, and events'],
    faqs:[['What is print on demand?','Products are produced after an order is placed rather than purchased as bulk inventory in advance.'],['Can I use my own artwork?','Yes. Upload your logo or design and preview it on supported products.'],['What products can I sell?','The catalog includes supported apparel, hats, stickers, drinkware, print products, and accessories.'],['How does shipping work?','Physical checkout collects the destination address, and the order record remains connected to production and fulfillment.']]
  }
};

const navLinks=Object.keys(pages).map(slug=>`<a href="/${slug}">${escapeHtml(pages[slug].eyebrow.replace('CUSTOM ','').replace('PRINT ON DEMAND FOR ','POD FOR '))}</a>`).join('');
const schema=(slug,page)=>{
  const canonical=`${SITE}/${slug}`;
  const primaryEntity=page.product?`${canonical}#product`:`${canonical}#service`;
  const graph=[
    {'@type':'WebPage','@id':`${canonical}#webpage`,name:page.title,description:page.description,url:canonical,primaryImageOfPage:{'@id':`${canonical}#primaryimage`},mainEntity:{'@id':primaryEntity}},
    {'@type':'ImageObject','@id':`${canonical}#primaryimage`,contentUrl:`${SITE}${page.image}`,caption:`MadeDeck ${page.eyebrow.toLowerCase()} page concept and product examples`},
    {'@type':'BreadcrumbList','@id':`${canonical}#breadcrumb`,itemListElement:[{'@type':'ListItem',position:1,name:'MadeDeck',item:`${SITE}/`},{'@type':'ListItem',position:2,name:page.eyebrow,item:canonical}]},
    {'@type':'FAQPage','@id':`${canonical}#faq`,mainEntity:page.faqs.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))}
  ];
  if(page.product){
    const offers=page.product.price
      ?{'@type':'Offer',url:canonical,priceCurrency:'USD',price:page.product.price,availability:'https://schema.org/InStock',itemCondition:'https://schema.org/NewCondition'}
      :{'@type':'AggregateOffer',url:canonical,priceCurrency:'USD',lowPrice:page.product.lowPrice,highPrice:page.product.highPrice,offerCount:page.product.offerCount};
    graph.push({'@type':'Product','@id':primaryEntity,name:page.product.name,description:page.description,sku:page.product.sku,image:`${SITE}${page.image}`,brand:{'@type':'Brand',name:'MadeDeck'},offers});
  }else graph.push({'@type':'Service','@id':primaryEntity,name:page.eyebrow,description:page.description,provider:{'@type':'Organization',name:'MadeDeck',url:SITE},areaServed:['US','CA'],url:canonical});
  return JSON.stringify({'@context':'https://schema.org','@graph':graph});
};

function renderSeoPage(slug){
  const page=pages[slug];if(!page)return null;
  const cards=page.uses.map((item,index)=>`<article><span>0${index+1}</span><h3>${escapeHtml(item)}</h3><p>Use MadeDeck to turn one clear idea into products people can order, share, and support.</p></article>`).join('');
  const benefits=page.benefits.map(item=>`<li>${escapeHtml(item)}</li>`).join('');
  const faqs=page.faqs.map(([q,a])=>`<details><summary>${escapeHtml(q)}</summary><p>${escapeHtml(a)}</p></details>`).join('');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(page.title)}</title><meta name="description" content="${escapeHtml(page.description)}"><link rel="canonical" href="${SITE}/${slug}"><meta property="og:type" content="website"><meta property="og:title" content="${escapeHtml(page.title)}"><meta property="og:description" content="${escapeHtml(page.description)}"><meta property="og:url" content="${SITE}/${slug}"><meta property="og:image" content="${SITE}${page.image}"><meta name="twitter:card" content="summary_large_image"><link rel="stylesheet" href="/seo-pages.css"><script type="application/ld+json">${schema(slug,page)}</script></head><body>
  <header class="seo-header"><a class="seo-brand" href="/" aria-label="MadeDeck home"><b>M</b>MadeDeck<span>.</span></a><button class="seo-menu" aria-expanded="false" aria-controls="seoNav">Menu</button><nav id="seoNav"><a href="/">Home</a>${navLinks}<a href="/?page=pricing#mdCommerce">Pricing</a></nav><a class="button compact" href="${page.ctaHref}">${escapeHtml(page.cta)}</a></header>
  <main><section class="seo-hero"><div class="hero-copy"><p class="kicker">${escapeHtml(page.eyebrow)}</p><h1>${escapeHtml(page.headline)}</h1><p class="lede">${escapeHtml(page.lede)}</p><div class="actions"><a class="button" href="${page.ctaHref}">${escapeHtml(page.cta)}</a><a class="button ghost" href="#options">${escapeHtml(page.secondary)}</a></div><p class="starting">${escapeHtml(page.starting)} · Final pricing and availability depend on the selected product and options.</p></div><figure><img src="${page.image}" alt="MadeDeck ${escapeHtml(page.eyebrow.toLowerCase())} page concept and product examples" width="1024" height="1536" fetchpriority="high"><figcaption>Page concept shown for inspiration. Current products and prices appear in MadeDeck.</figcaption></figure></section>
  <section class="proof" aria-label="MadeDeck benefits"><span>Start free</span><span>No inventory required to begin</span><span>Human production review</span><span>Connected checkout and fulfillment</span></section>
  <section class="content" id="options"><div><p class="kicker">FROM IDEA TO PRODUCT</p><h2>Make it once. Order it or sell it.</h2><p>Choose a supported product, add artwork, review the result, then order it directly or save it to your MadeDeck store.</p><ol class="steps"><li><b>1</b>Choose a product</li><li><b>2</b>Add your artwork</li><li><b>3</b>Preview and review</li><li><b>4</b>Order or publish</li></ol></div><aside><h3>What you get</h3><ul>${benefits}</ul><a class="text-link" href="${page.ctaHref}">Open MadeDeck →</a></aside></section>
  <section class="use-cases"><div class="section-heading"><p class="kicker">BUILT FOR REAL USE</p><h2>${escapeHtml(page.eyebrow.replace('CUSTOM ','').replace('PRINT ON DEMAND FOR ','MadeDeck for '))} for more than one kind of customer.</h2></div><div class="cards">${cards}</div></section>
  <section class="link-hub"><p class="kicker">EXPLORE MADEDECK</p><h2>One platform. Six ways in.</h2><div>${navLinks}</div></section>
  <section class="faq"><div><p class="kicker">COMMON QUESTIONS</p><h2>Clear answers before you start.</h2><p>Exact availability, timing, and price are confirmed in the current product and checkout flow.</p></div><div>${faqs}</div></section>
  <section class="final-cta"><div><p class="kicker">IDEAS INTO REAL THINGS</p><h2>${escapeHtml(page.headline)}</h2></div><a class="button" href="${page.ctaHref}">${escapeHtml(page.cta)}</a></section></main>${renderFooter()}<script src="/seo-pages.js" defer></script></body></html>`;
}

function renderFooter(){return `<footer class="seo-footer"><div><a class="seo-brand" href="/"><b>M</b>MadeDeck<span>.</span></a><p>Create · Sell · Print · Run it.</p></div><div><h2>Products</h2>${navLinks}</div><div><h2>Company</h2><a href="/terms">Terms of Service</a><a href="/privacy">Privacy</a><a href="/shipping-and-returns">Shipping and returns</a><a href="/security">Security</a></div><div><h2>Get started</h2><a href="/studio">Open Studio</a><a href="/?page=join">Start a store</a><a href="/?page=pricing#mdCommerce">Pricing</a></div></footer>`}

const policies={
  terms:{title:'MadeDeck Terms of Service',description:'Terms governing MadeDeck accounts, storefronts, products, orders, production, and fulfillment.',sections:[['Orders and production','Product availability, decoration options, production estimates, shipping charges, and final pricing are shown in the applicable order flow. Orders may be reviewed for artwork, production, safety, fraud, or policy issues before fulfillment.'],['Physical delivery','A valid shipping address is required for physical products. Customers are responsible for accurate recipient and destination information. Delivery estimates are not guarantees and may change because of production, carrier, address, or force-majeure delays.'],['Storefronts and sellers','Account holders are responsible for the products, artwork, descriptions, rights, pricing choices, and customer promises they publish. MadeDeck may remove or pause content that violates law, intellectual-property rights, platform policy, or production requirements.'],['Payments and refunds','Payment processing may be provided by Stripe or another disclosed processor. Refund, cancellation, replacement, and reprint eligibility depends on production status, customization, defect evidence, carrier events, and the policy presented with the order.'],['Acceptable use and intellectual property','You must have the right to use submitted names, logos, images, and other content. You may not use MadeDeck for unlawful, deceptive, infringing, abusive, or harmful activity.'],['Service changes','Features, catalog items, suppliers, prices, limits, and integrations may change. Material terms will be updated on this page with a revised effective date.']]},
  privacy:{title:'MadeDeck Privacy Policy',description:'How MadeDeck handles account, storefront, order, shipping, payment, production, and usage information.',sections:[['Information we collect','MadeDeck may collect account and contact information; store, product, artwork, and design data; order and recipient information; shipping addresses; support communications; service events; and device, security, and usage information.'],['Payments','Payment card details are handled by the payment processor rather than stored by MadeDeck as raw card data. MadeDeck receives transaction identifiers, status, amount, currency, and related order information needed to operate the service.'],['How information is used','Information is used to authenticate users, isolate accounts, provide Studio and storefront features, process orders, collect payment, review artwork, produce and ship products, provide support, prevent abuse, measure service performance, and meet legal obligations.'],['Service providers','MadeDeck may share necessary information with hosting, database, email, payment, analytics, production, shipping, storage, and support providers. Providers receive only the information needed for their role and are subject to their own terms and privacy practices.'],['Retention and deletion','Records are kept only as long as reasonably needed for active services, production and delivery, accounting, security, disputes, legal obligations, and backup integrity. Deletion requests may be limited where retention is required.'],['Your choices','You may request access, correction, or deletion of eligible personal information and may control optional communications where offered. Essential account, security, order, and transaction notices cannot always be disabled.']]},
  'shipping-and-returns':{title:'Shipping Production Returns and Cancellations',description:'MadeDeck shipping, production, cancellation, return, reprint, and refund information.',sections:[['Shipping addresses','Physical-product checkout requires a valid recipient and shipping address. Review the address before payment. Address corrections may not be possible after production or carrier handoff.'],['Production timing','Production begins after payment, artwork readiness, and any required review. Product-page estimates are planning guidance; the current estimate shown with the order controls.'],['Custom products','Because customized products are made for a specific order, change-of-mind returns may be limited after production begins.'],['Problems with an order','Contact support promptly with the order reference, photos, packaging details, and a description of the issue. Confirmed production defects, damage, missing items, or incorrect items may qualify for a reprint, replacement, credit, or refund.'],['Cancellations','Cancellation requests are reviewed against the order status. Orders already in production or completed may not be cancellable.'],['Carrier events','MadeDeck will help investigate eligible lost, damaged, or misdelivered shipments, but carrier scans, destination accuracy, and recipient availability can affect the available remedy.']]},
  security:{title:'MadeDeck Security and Responsible Disclosure',description:'MadeDeck security practices, account isolation, payment handling, and responsible disclosure information.',sections:[['Security approach','MadeDeck uses account-scoped authorization, authenticated server routes, audit-oriented records, transport encryption provided by the production host, and third-party payment processing. Security controls are reviewed and improved as the service changes.'],['Account isolation','MadeDeck is designed to keep account, store, design, product, and order activity scoped to the authorized tenant. Access-control tests include rejection of cross-account identifiers.'],['Payments','Payment checkout is handled through Stripe. MadeDeck does not intentionally collect raw card numbers in its application forms.'],['Reporting a concern','If you believe you found a vulnerability, contact MadeDeck privately with reproduction steps, affected URLs, and potential impact. Do not access other users’ data, disrupt service, or publicly disclose an unresolved issue.'],['No unsupported claims','This page describes current design intent and verified controls; it does not claim a certification, independent penetration test, insurance policy, or universal encryption coverage unless explicitly stated.']]}
};
function renderPolicyPage(slug){const page=policies[slug];if(!page)return null;const body=page.sections.map(([h,p])=>`<section><h2>${escapeHtml(h)}</h2><p>${escapeHtml(p)}</p></section>`).join('');return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(page.title)} | MadeDeck</title><meta name="description" content="${escapeHtml(page.description)}"><link rel="canonical" href="${SITE}/${slug}"><link rel="stylesheet" href="/seo-pages.css"></head><body><header class="seo-header"><a class="seo-brand" href="/"><b>M</b>MadeDeck<span>.</span></a><nav><a href="/">Home</a><a href="/online-merch-store">Merch stores</a><a href="/print-on-demand-for-small-business">Small business</a></nav><a class="button compact" href="/?page=join">Get started</a></header><main class="policy"><p class="kicker">MADEDECK POLICIES</p><h1>${escapeHtml(page.title)}</h1><p class="lede">${escapeHtml(page.description)}</p><p class="effective">Effective September 21, 2026.</p>${body}</main>${renderFooter()}<script src="/seo-pages.js" defer></script></body></html>`}

module.exports={pages,policies,renderSeoPage,renderPolicyPage};
