'use strict';
const express=require('express');
const parse=value=>{try{return typeof value==='string'?JSON.parse(value):value}catch{return null}};
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const slug=value=>String(value||'').trim().toLowerCase().replace(/[^a-z0-9-]/g,'').slice(0,60);
const RESERVED_ROOTS=new Set(['api','member','studio','store','account-billing','account-billing.html','health','login','logout','admin','assets','mockups','premades','private','public','docs','favicon.ico','robots.txt']);
function createStorefrontRouter({db}){
 const router=express.Router();
 async function storeFor(raw){const key=slug(raw);if(!key)return null;const [accounts]=await db().execute("SELECT id,account_key,name,metadata_json FROM accounts WHERE status='active' AND (account_key=? OR JSON_UNQUOTE(JSON_EXTRACT(metadata_json,'$.store.slug'))=?) LIMIT 1",[key,key]);const account=accounts[0];if(!account)return null;const metadata=parse(account.metadata_json)||{},store=metadata.store||{};if(!store.storefront_published)return null;const keys=(Array.isArray(store.published_product_keys)?store.published_product_keys:[]).slice(0,Math.max(1,Number(metadata.product_limit||3)));let products=[];if(keys.length){const marks=keys.map(()=>'?').join(',');const [rows]=await db().execute(`SELECT product_key,name,retail_price,product_json FROM tenant_saved_products WHERE account_id=? AND product_key IN (${marks})`,[account.id,...keys]);products=keys.map(k=>rows.find(row=>row.product_key===k)).filter(Boolean).map(row=>({...row,product:parse(row.product_json)||{},product_json:undefined}))}return{account_id:account.id,account_key:account.account_key,name:store.name||account.name,slug:store.slug||account.account_key,bio:store.bio||'',daily_message:store.daily_message||'',logo_data:store.logo_data||'',links:Array.isArray(store.links)?store.links:[],products}}
 function storeHtml(store){const cards=store.products.map(row=>{const base=String(row.product.base_product||row.product.product_key||'tee').replace(/[^a-z0-9_-]/gi,'');return`<article><h2>${esc(row.name)}</h2><p>${esc(row.product.description||'Made with MadeDeck')}</p><strong>$${Number(row.retail_price||0).toFixed(2)}</strong><a href="/?product=${encodeURIComponent(base)}#designer">Customize</a></article>`}).join('')||'<p>This store has no published products yet.</p>';const links=store.links.map(item=>`<a href="${esc(item.url)}" rel="noopener noreferrer">${esc(item.label)}</a>`).join('');const publicUrl=`/${encodeURIComponent(store.slug)}`;const qr=`https://quickchart.io/qr?size=180&margin=1&text=${encodeURIComponent(publicUrl)}`;return`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(store.name)} · MadeDeck</title><style>body{margin:0;font:16px Arial;color:#111;background:#f4f4ef}header,main{max-width:1100px;margin:auto;padding:28px}header{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:18px;border-bottom:2px solid #111}.logo{width:76px;height:76px;object-fit:contain;background:#fff;border:1px solid #bbb}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:18px}article{background:#fff;border:2px solid #111;padding:20px;box-shadow:6px 6px 0 #caff00}article a{display:block;margin-top:18px;padding:12px;background:#111;color:#fff;text-align:center;text-decoration:none;font-weight:900}.links{display:flex;gap:12px;flex-wrap:wrap}.links a{color:#111}.daily{padding:14px;background:#caff00;font-weight:800}.qr{background:#fff;border:2px solid #111;padding:8px;text-align:center}.qr img{display:block;width:112px;height:112px}.qr small{display:block;margin-top:5px;font-size:9px;font-weight:900}@media(max-width:680px){header{grid-template-columns:auto 1fr}.qr{grid-column:1/-1;display:flex;align-items:center;gap:12px;text-align:left}.qr img{width:86px;height:86px}}</style></head><body><header>${store.logo_data?`<img class="logo" src="${esc(store.logo_data)}" alt="${esc(store.name)} logo">`:''}<div><h1>${esc(store.name)}</h1><p>${esc(store.bio)}</p><nav class="links">${links}</nav></div><div class="qr"><img src="${qr}" alt="QR code for ${esc(store.name)}"><small>Share this store</small></div></header><main>${store.daily_message?`<p class="daily">${esc(store.daily_message)}</p>`:''}<section class="grid">${cards}</section></main></body></html>`}
 async function sendStore(req,res,next){try{const store=await storeFor(req.params.slug);if(!store)return res.status(404).type('html').send('<h1>Store not found</h1>');res.set('Cache-Control','no-store');res.type('html').send(storeHtml(store))}catch(error){next(error)}}
 router.get('/api/public/store/:slug',async(req,res,next)=>{try{const store=await storeFor(req.params.slug);if(!store)return res.status(404).json({ok:false,error:'store_not_found'});const {account_id,...publicStore}=store;res.json({ok:true,store:publicStore})}catch(error){next(error)}});
 router.get('/store/:slug',sendStore);
 router.get('/:slug',async(req,res,next)=>{const key=slug(req.params.slug);if(!key||RESERVED_ROOTS.has(key))return next();return sendStore(req,res,next)});
 return router;
}
module.exports={createStorefrontRouter};
